dist: xenial
sudo: false

language: node_js

node_js:
  - "10.13.0"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test


before_install:
  - npm conf set strict-ssl false
  - npm install -g npm@6.4.1
  - export DISPLAY=:99
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"


install:
  - npm i --clang=1
  - cd test && npm i --clang=1
  - cd ..


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


script:
  - cd test && npm test
  - cd ..
